# Generated by Django 4.2.4 on 2023-09-03 15:05

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gnomehacks", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="hackfest",
            old_name="question",
            new_name="location",
        ),
        migrations.RenameField(
            model_name="hackfest",
            old_name="question_text",
            new_name="title",
        ),
        migrations.AddField(
            model_name="hackfest",
            name="end",
            field=models.DateTimeField(default=datetime.datetime(1970, 1, 1, 0, 0)),
        ),
        migrations.AddField(
            model_name="hackfest",
            name="start",
            field=models.DateTimeField(default=datetime.datetime(1970, 1, 1, 0, 0)),
        ),
    ]
