# Generated by Django 4.2.4 on 2023-09-03 15:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gnomehacks", "0002_rename_question_hackfest_location_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="location",
            name="description",
            field=models.TextField(
                max_length=4194304,
                validators=[django.core.validators.MaxLengthValidator(4194304)],
            ),
        ),
    ]
