# Generated by Django 4.2.4 on 2023-09-03 16:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gnomehacks", "0003_alter_location_description"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="hackfest",
            name="attendees",
        ),
        migrations.RemoveField(
            model_name="hackfest",
            name="trusted_users",
        ),
        migrations.AddField(
            model_name="hackfest",
            name="organizer",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="gnomehacks.user",
            ),
        ),
        migrations.CreateModel(
            name="TrustedUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "hackfest",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="gnomehacks.hackfest",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="gnomehacks.user",
                    ),
                ),
            ],
        ),
    ]
