# Generated by Django 4.2.4 on 2023-09-03 18:30

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gnomehacks", "0007_alter_hackfest_organizer_alter_trusteduser_user_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hackfest",
            name="end",
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name="hackfest",
            name="start",
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
